# Core
set -g mouse on
set -g detach-on-destroy off

# Terminal
set -g default-terminal "tmux-256color"
# what does this do?
# set -as terminal-features ",tmux-256color:RGB"

# Prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Indexing
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Copy mode
set -g mode-keys vi
bind -T copy-mode-vi Escape send-keys -X cancel

# Key bindings
bind r source-file "~/.config/tmux/tmux.conf" \; display-message "Config reloaded!"
bind -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"
bind Q confirm-before -p "Kill the entire tmux server? (y/n)" "kill-server"
bind x kill-pane
bind X kill-window
bind -r j previous-window
bind -r k next-window
bind y display-popup -d "#{pane_current_path}" -w 80% -h 80% -E "lazygit"

# Status
set -g status-position top
set -g status-justify absolute-centre
# transparent bg
set -g status-style "bg=default"

# session name on left
set -g status-left "#S "
# nothing on right
set -g status-right ""

# Unfocused: grey; Focused: green + bold
setw -g window-status-style "fg=brightblack"
setw -g window-status-current-style "fg=green,bg=default,bold"
