general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
# ── Normal font ────────────────────────────────
normal = { family = "JetBrainsMono Nerd Font", style = "SemiBold" }

# ── Bold font ─────────────────────────────────
bold = { family = "JetBrainsMono Nerd Font", style = "ExtraBold" }

# ── Italic font ───────────────────────────────
italic = { family = "JetBrainsMono Nerd Font", style = "ExtraBold Italic" }

# ── Bold + Italic font ────────────────────────
bold_italic = { family = "JetBrainsMono Nerd Font", style = "ExtraBold Italic" }

size = 14

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy" }
]

# trying nu rn
[shell]
program = "/usr/bin/nu"
args = ["-l"]

