-- Auto-generated by omarchy theme-set hook
-- Do not edit manually
return {
    base00 = "#1e1e2e",
    base01 = "#45475a",
    base02 = "#585b70",
    base03 = "#585b70",
    base04 = "#bac2de",
    base05 = "#cdd6f4",
    base06 = "#cdd6f4",
    base07 = "#a6adc8",
    base08 = "#f38ba8",
    base09 = "#f9e2af",
    base0A = "#a6e3a1",
    base0B = "#89b4fa",
    base0C = "#94e2d5",
    base0D = "#f5c2e7",
    base0E = "#f5c2e7",
    base0F = "#f5c2e7",
}
