-- Transparent ANSI Neovim Colorscheme
-- Save to: ~/.config/nvim/colors/ansi.lua
-- Usage: vim.cmd('colorscheme ansi')

vim.cmd('hi clear')
if vim.fn.exists('syntax_on') == 1 then
  vim.cmd('syntax reset')
end

vim.o.background = 'dark'
vim.g.colors_name = 'ansi-custom'
vim.o.termguicolors = false

local hi = function(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

local link = function(from, to)
  vim.api.nvim_set_hl(0, from, { link = to })
end

-- Editor Elements (with transparency)
hi('NonText', { ctermfg = 0 })
hi('Ignore', {})
hi('Underlined', { underline = true })
hi('Bold', { bold = true })
hi('Italic', { italic = true })
hi('StatusLine', { ctermfg = 15, ctermbg = 8 })
hi('StatusLineNC', { ctermfg = 15, ctermbg = 0 })
hi('VertSplit', { ctermfg = 8 })
hi('TabLine', { ctermfg = 7 })
hi('TabLineFill', { ctermfg = 0 })
hi('TabLineSel', { ctermfg = 11, bold = true })
hi('Title', { ctermfg = 4, bold = true })
hi('CursorLine', {})
hi('Cursor', { reverse = true })
hi('CursorColumn', {})
hi('LineNr', { ctermfg = 8 })
hi('CursorLineNr', { ctermfg = 6, bold = true })
hi('Visual', { ctermbg = 8, ctermfg = 15, bold = true })
hi('VisualNOS', { ctermbg = 8, ctermfg = 15, bold = true })
hi('Pmenu', { ctermfg = 15 })
hi('PmenuSbar', { ctermfg = 7 })
hi('PmenuSel', { ctermfg = 15, bold = true, reverse = true })
hi('PmenuThumb', { ctermfg = 7, reverse = true })
hi('FoldColumn', { ctermfg = 7 })
hi('Folded', { ctermfg = 12 })
hi('WildMenu', { ctermbg = 0, ctermfg = 15 })
hi('SpecialKey', { ctermfg = 0 })
hi('IncSearch', { ctermbg = 1, ctermfg = 0 })
hi('CurSearch', { ctermbg = 3, ctermfg = 0 })
hi('Search', { ctermbg = 11, ctermfg = 0 })
hi('Directory', { ctermfg = 4 })
hi('MatchParen', { ctermfg = 3, bold = true, underline = true })
hi('SpellBad', { undercurl = true })
hi('SpellCap', { undercurl = true })
hi('SpellLocal', { undercurl = true })
hi('SpellRare', { undercurl = true })
hi('ColorColumn', { ctermbg = 8 })
hi('SignColumn', { ctermfg = 7 })
hi('ModeMsg', { ctermfg = 0, ctermbg = 15, bold = true })
hi('MoreMsg', { ctermfg = 4 })
hi('Question', { ctermfg = 4 })
hi('QuickFixLine', { ctermfg = 14, reverse = true })
hi('Conceal', { ctermfg = 8 })
hi('ToolbarLine', { ctermfg = 15 })
hi('ToolbarButton', { ctermfg = 15, reverse = true })
hi('debugPC', { ctermfg = 7 })
hi('debugBreakpoint', { ctermfg = 8 })
hi('ErrorMsg', { ctermfg = 1, bold = true, italic = true })
hi('WarningMsg', { ctermfg = 11 })
hi('DiffAdd', { ctermbg = 10, ctermfg = 0 })
hi('DiffChange', { ctermbg = 12, ctermfg = 0 })
hi('DiffDelete', { ctermbg = 9, ctermfg = 0 })
hi('DiffText', { ctermbg = 14, ctermfg = 0 })
hi('diffAdded', { ctermfg = 10 })
hi('diffRemoved', { ctermfg = 9 })
hi('diffChanged', { ctermfg = 12 })
hi('diffOldFile', { ctermfg = 11 })
hi('diffNewFile', { ctermfg = 13 })
hi('diffFile', { ctermfg = 12 })
hi('diffLine', { ctermfg = 7 })
hi('diffIndexLine', { ctermfg = 14 })
hi('healthError', { ctermfg = 1 })
hi('healthSuccess', { ctermfg = 2 })
hi('healthWarning', { ctermfg = 3 })

-- LSP and diagnostic highlights (transparent backgrounds)
hi('DiagnosticError', { ctermfg = 1 })
hi('DiagnosticWarn', { ctermfg = 11 })
hi('DiagnosticInfo', { ctermfg = 4 })
hi('DiagnosticHint', { ctermfg = 6 })
hi('DiagnosticOk', { ctermfg = 2 })
hi('DiagnosticUnderlineError', { ctermfg = 1, undercurl = true })
hi('DiagnosticUnderlineWarn', { ctermfg = 11, undercurl = true })
hi('DiagnosticUnderlineInfo', { ctermfg = 4, undercurl = true })
hi('DiagnosticUnderlineHint', { ctermfg = 6, undercurl = true })
hi('DiagnosticUnderlineOk', { ctermfg = 2, undercurl = true })
hi('DiagnosticVirtualTextError', { ctermfg = 1 })
hi('DiagnosticVirtualTextWarn', { ctermfg = 11 })
hi('DiagnosticVirtualTextInfo', { ctermfg = 4 })
hi('DiagnosticVirtualTextHint', { ctermfg = 6 })
hi('DiagnosticVirtualTextOk', { ctermfg = 2 })

-- LSP semantic highlights
hi('LspReferenceText', { underline = true })
hi('LspReferenceRead', { underline = true })
hi('LspReferenceWrite', { underline = true, bold = true })
hi('LspSignatureActiveParameter', { ctermfg = 11, bold = true })
hi('LspCodeLens', { ctermfg = 8, italic = true })
hi('LspCodeLensSeparator', { ctermfg = 8 })
hi('LspInlayHint', { ctermfg = 8, italic = true })

-- Transparent backgrounds everywhere
hi('Normal', {})
hi('NormalNC', {})
hi('NormalFloat', { ctermfg = 15 })
hi('FloatBorder', { ctermfg = 7 })
hi('FloatTitle', { ctermfg = 4, bold = true })

-- Syntax
hi('Comment', { ctermfg = 8, italic = true })
hi('Constant', { ctermfg = 3 })
hi('Error', { ctermfg = 1 })
hi('Identifier', { ctermfg = 9 })
hi('Function', { ctermfg = 4 })
hi('Special', { ctermfg = 13 })
hi('Statement', { ctermfg = 5 })
hi('String', { ctermfg = 2 })
hi('Character', { ctermfg = 2 })
hi('Number', { ctermfg = 3 })
hi('Float', { ctermfg = 3 })
hi('Operator', { ctermfg = 6 })
hi('Boolean', { ctermfg = 3 })
hi('Label', { ctermfg = 14 })
hi('Keyword', { ctermfg = 5 })
hi('Exception', { ctermfg = 5 })
hi('Conditional', { ctermfg = 5 })
hi('Repeat', { ctermfg = 5 })
hi('PreProc', { ctermfg = 13 })
hi('Include', { ctermfg = 5 })
hi('Define', { ctermfg = 5 })
hi('Macro', { ctermfg = 5 })
hi('StorageClass', { ctermfg = 11 })
hi('Structure', { ctermfg = 11 })
hi('Typedef', { ctermfg = 11 })
hi('Todo', { ctermfg = 0, ctermbg = 9, bold = true })
hi('Type', { ctermfg = 11 })
hi('Delimiter', { ctermfg = 15 })
hi('Tag', { ctermfg = 5 })
hi('SpecialChar', { ctermfg = 13 })

-- Treesitter highlighting
hi('@variable', { ctermfg = 15 })
hi('@variable.builtin', { ctermfg = 1 })
hi('@variable.parameter', { ctermfg = 1 })
hi('@variable.member', { ctermfg = 1 })
hi('@constant.builtin', { ctermfg = 5 })
hi('@string.regexp', { ctermfg = 1 })
hi('@string.escape', { ctermfg = 6 })
hi('@string.special.url', { ctermfg = 4, underline = true })
hi('@string.special.symbol', { ctermfg = 13 })
hi('@type.builtin', { ctermfg = 3 })
hi('@property', { ctermfg = 1 })
hi('@function.builtin', { ctermfg = 5 })
hi('@constructor', { ctermfg = 11 })
hi('@keyword.coroutine', { ctermfg = 1 })
hi('@keyword.function', { ctermfg = 5 })
hi('@keyword.return', { ctermfg = 5 })
hi('@keyword.export', { ctermfg = 14 })
hi('@punctuation.bracket', { ctermfg = 15 })
hi('@comment.error', { ctermbg = 9, ctermfg = 0 })
hi('@comment.warning', { ctermbg = 11, ctermfg = 0 })
hi('@comment.todo', { ctermbg = 12, ctermfg = 0 })
hi('@comment.note', { ctermbg = 14, ctermfg = 0 })
hi('@markup', { ctermfg = 15 })
hi('@markup.strong', { ctermfg = 15, bold = true })
hi('@markup.italic', { ctermfg = 15, italic = true })
hi('@markup.strikethrough', { ctermfg = 15, strikethrough = true })
hi('@markup.heading', { ctermfg = 4, bold = true })
hi('@markup.quote', { ctermfg = 6 })
hi('@markup.math', { ctermfg = 4 })
hi('@markup.link.url', { ctermfg = 5, underline = true })
hi('@markup.raw', { ctermfg = 14 })
hi('@markup.list.checked', { ctermfg = 2 })
hi('@markup.list.unchecked', { ctermfg = 7 })
hi('@tag', { ctermfg = 5 })
hi('@tag.builtin', { ctermfg = 6 })
hi('@tag.attribute', { ctermfg = 4 })
hi('@tag.delimiter', { ctermfg = 15 })

-- Treesitter links
link('@variable.parameter.builtin', '@variable.parameter')
link('@constant', 'Constant')
link('@constant.macro', 'Macro')
link('@module', 'Structure')
link('@module.builtin', 'Special')
link('@label', 'Label')
link('@string', 'String')
link('@string.special', 'Special')
link('@character', 'Character')
link('@character.special', 'SpecialChar')
link('@boolean', 'Boolean')
link('@number', 'Number')
link('@number.float', 'Float')
link('@type', 'Type')
link('@type.definition', 'Type')
link('@attribute', 'Constant')
link('@attribute.builtin', 'Constant')
link('@function', 'Function')
link('@function.call', 'Function')
link('@function.method', 'Function')
link('@function.method.call', 'Function')
link('@operator', 'Operator')
link('@keyword', 'Keyword')
link('@keyword.operator', 'Operator')
link('@keyword.import', 'Include')
link('@keyword.type', 'Keyword')
link('@keyword.modifier', 'Keyword')
link('@keyword.repeat', 'Repeat')
link('@keyword.debug', 'Exception')
link('@keyword.exception', 'Exception')
link('@keyword.conditional', 'Conditional')
link('@keyword.conditional.ternary', 'Operator')
link('@keyword.directive', 'PreProc')
link('@keyword.directive.define', 'Define')
link('@punctuation.delimiter', 'Delimiter')
link('@punctuation.special', 'Special')
link('@comment', 'Comment')
link('@comment.documentation', 'Comment')
link('@markup.underline', 'Underlined')
link('@markup.link', 'Tag')
link('@markup.link.label', 'Label')
link('@markup.list', 'Special')
link('@diff.plus', 'diffAdded')
link('@diff.minus', 'diffRemoved')
link('@diff.delta', 'diffChanged')
